const m=require("mongoose"),S=m.Schema;
exports.User=m.model("User",new S({name:{type:String,required:true},email:{type:String,unique:true,lowercase:true},password:{type:String,required:true,select:false},role:{type:String,enum:["admin","doctor","patient"],default:"patient"},phone:String,language:{type:String,enum:["en","hi"],default:"en"},isActive:{type:Boolean,default:true}},{timestamps:true}));
exports.Doctor=m.model("DoctorProfile",new S({user:{type:S.Types.ObjectId,ref:"User",unique:true},specialty:String,department:String,consultationFee:Number,slotDuration:{type:Number,default:30},schedule:Array,bio:String},{timestamps:true}));
exports.Patient=m.model("PatientProfile",new S({user:{type:S.Types.ObjectId,ref:"User",unique:true},bloodGroup:String,allergies:[String],medicalHistory:[String],emergencyContact:Object},{timestamps:true}));
const A=new S({patient:{type:S.Types.ObjectId,ref:"User"},doctor:{type:S.Types.ObjectId,ref:"User"},startAt:{type:Date,index:true},endAt:Date,reason:String,status:{type:String,enum:["booked","confirmed","completed","cancelled","no-show"],default:"booked"},type:{type:String,enum:["in-person","telemedicine"],default:"in-person"},noShowRisk:{type:String,enum:["low","medium","high"],default:"low"},reminderSentAt:Date,roomId:String},{timestamps:true});A.index({doctor:1,startAt:1,status:1},{unique:true,partialFilterExpression:{status:{$in:["booked","confirmed"]}}});exports.Appointment=m.model("Appointment",A);
exports.Prescription=m.model("Prescription",new S({patient:{type:S.Types.ObjectId,ref:"User"},doctor:{type:S.Types.ObjectId,ref:"User"},appointment:S.Types.ObjectId,diagnosis:String,medicines:Array,verificationCode:{type:String,unique:true}},{timestamps:true}));
exports.Audit=m.model("AuditLog",new S({actor:{type:S.Types.ObjectId,ref:"User"},action:String,entityType:String,entityId:String,metadata:Object,ip:String,userAgent:String},{timestamps:true}));
exports.Bed=m.model("Bed",new S({ward:String,number:String,status:{type:String,enum:["vacant","occupied","maintenance"],default:"vacant"},patient:S.Types.ObjectId},{timestamps:true}));
exports.Claim=m.model("InsuranceClaim",new S({patient:S.Types.ObjectId,provider:String,policyNumber:String,amount:Number,status:{type:String,enum:["pending","approved","rejected"],default:"pending"},notes:String},{timestamps:true}));
